version: '2'

services:
   db:
     build: ./wpdb_image
     image: wpdb_image
     volumes:
       - db_data:/var/lib/mysql
       - ./wpdb_image:/home/dump
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

#   npm:
#     image: node:7.4
#     volumes:
#      - ./foundationpress:/var/www/html/wp-content/themes/foundationpress
     
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wp-plugins:/var/www/html/wp-content/plugins
       - ./foundationpress:/var/www/html/wp-content/themes/foundationpress
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data:
