version: '2'

services:
   db:
     build: ./docker-images/openbw_db
     image: openbw_db
     volumes:
       - db_data:/var/lib/mysql
       - ./docker-images/openbw_db:/home/dump
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

#   npm:
#     image: node:7.4
#     volumes:
#      - ./foundationpress:/var/www/html/wp-content/themes/foundationpress
     
   wordpress:
     depends_on:
       - db
     build: ./docker-images/openbw_wp
     image: openbw_wp
     volumes:
       - ./wp-plugins:/var/www/html/wp-content/plugins
       - ./foundationpress:/var/www/html/wp-content/themes/foundationpress
       - ./bw:/var/www/html/bw
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data:
